---
- name: openscap client
  hosts: ip-10-0-1-237.us-east-2.compute.internal
  remote_user: ec2-user
  gather_facts: true
  become: yes
  become_user: root
  become_method: sudo
  vars:
    satellite_server: ip-10-0-0-12.us-east-2.compute.internal
    satellite_username: admin
    satellite_password: r3dh4t1!
    capsule_server: ip-10-0-0-12.us-east-2.compute.internal
    policy_name: test_policy
  roles:
        - openscap_role
